// Copyright (c) 2017 Computer Vision Center (CVC) at the Universitat Autonoma
// de Barcelona (UAB).
//
// This work is licensed under the terms of the MIT license.
// For a copy, see <https://opensource.org/licenses/MIT>.

#pragma once

#include "LidarDescription.generated.h"

USTRUCT()
struct CARLA_API FLidarDescription
{
  GENERATED_BODY()

  /// Number of lasers.
  UPROPERTY(EditAnywhere)
  uint32 Channels = 32u;

  /// Measure distance in meters.
  UPROPERTY(EditAnywhere)
  float Range = 200.0f;

  /// Points generated by each lasers per second.
  /// Total points generated should multiply by Channels
  UPROPERTY(EditAnywhere)
  uint32 PointsPerSecond = 36000u;

  /// Lidar rotation frequency.
  UPROPERTY(EditAnywhere)
  float RotationFrequency = 10.0f;

  /// Upper laser angle, counts from horizontal, positive values means above
  /// horizontal line.
  UPROPERTY(EditAnywhere)
  float UpperFovLimit = 10.0f;

  /// Lower laser angle, counts from horizontal, negative values means under
  /// horizontal line.
  UPROPERTY(EditAnywhere)
  float LowerFovLimit = -30.0f;

  /// An array specifies the veticle angle of each channel.
  /// If this array is empty, VerticleAngles will be calculated by UpperFovLimit and LowerForLimit
  UPROPERTY(EditAnywhere)
  TArray<float> VerticleAngles{};

  /// Wether to show debug points of laser hits in simulator.
  UPROPERTY(EditAnywhere)
  bool ShowDebugPoints = false;
};
